### PR TITLE
Suppress weight labels from rendering

### PR DESCRIPTION
**Pull request by cyberscribe**
Adds a extensible options array to accomplish this.

### CODE REVIEW

**Comment by clue** [comment]
Thanks for your PR, much appreciated :+1: 

I think having this feature makes perfect sense, but I have to admit I'm not a big fan of the current implementation.

The related code autogenerates an edge label. I think it makes more sense to split this code off and possibly pass a custom instance into the dot exporter.

See also https://github.com/clue/graph/issues/114 and #14.

**Comment by cyberscribe** [comment]
Feel free to re-implement. I just needed a quick way to turn off those annoying labels in dot. Merge or discard--up to you.

**Comment by clue** [comment]
Didn't mean to discourage your contribution, this PR is much appreciated :+1:

I think it makes perfect sense to omit the weight in certain cases. And it probably also makes sense to omit the other edges attributes (flow and capacity) in similar cases.

What do you think about this?

**Comment by cyberscribe** [comment]
I agree. This was the intent of implementing a simple associative array so that you can extend it into any number of "toggle switch" options.

If you don't like the direct access within the class, we could implement a getOption() method that checks if it's set (false if not) and returns the value. We could then wrap all conditional output in a getOption() call beforehand, and give a list of valid options for use.

**Comment by clue** [comment]
I'm sure this is going to sufficient once https://github.com/clue/graph/issues/114 has been implemented.

This would mean we would have to specify which attributes get exported which way. This is certainly beyond our control for special attributes, so I think it makes more sense to provide a simple "export mathematical properties like previously"-implementation and a "do not export anything"-implementation and an interface for custom implementations.

**Pull request closed without merging**
