### PR TITLE
GraphViz: add charset option to base64 image string.

### PR DESCRIPTION
**Pull request by Ithilias**

### CODE REVIEW

**Comment by clue** [comment]
Thanks for filing this PR!

However, the motivation is a bit unclear to me, so perhaps you can elaborate? When is this needed? When would one change the charset attribute?

**Comment by Ithilias** [comment]
Browser will decode the base64 string with the default browser charset, which often is iso-8859-1. 
It may not be the case that the svg file is encoded with that encoding. This change allows you to specify the encoding for the browser.

**Comment by clue** [comment]
Thanks, I understand :-) Can you provide a reproducible test case for this?

**Comment by Ithilias** [comment]
```
use Fhaculty\Graph\Graph;
use Graphp\GraphViz\GraphViz;

$graph = new Graph();
$graph->setAttribute('charset', 'UTF-8');

$modelvertex = $graph->createVertex("üuu");
$modelvertex->setAttribute('graphviz.color', 'blue');
$modeltypevertex = $graph->createVertex("äaa");
$edge = $modelvertex->createEdgeTo($modeltypevertex);
$edge->setAttribute('graphviz.color', 'grey');

$graphviz = new GraphViz();
$graphviz->setFormat("svg");
echo $graphviz->createImageHtml($graph);
```
This is an example which shows encoding problems with german umlauts.
encodingproblem

**Comment by clue** [comment]
Thanks, I'll play around with this a bit :+1: 

At first sight, I'm tempted to promote (enforce) UTF-8 encoding here and remove the ctor argument, as I see little value in providing any other encoding.

I'll (try to) get back to this *soon-ish*.

**Comment by clue** [comment]
@Ithilias Again thank you for filing this PR and for your patience!

I agree that this feature makes perfect sense and have just merged a slightly modified version with #27 (with proper attribution of course) :shipit: :tada: 

I've added some documentation to emphasize that UTF-8 is the default. I've removed the constructor argument, one can now use the the `charset` attribute to change to a different encoding instead, but this is usually not recommended.

Again, thank you! :+1:

**Pull request closed without merging**
