### PR TITLE
Allow setting of graph name via graphviz.name attribute

### PR DESCRIPTION
**Pull request by rhelms**
graphp/graphviz#3

### CODE REVIEW

**Comment by clue** [comment]
Thanks for filing this PR! :+1: 

Does it make sense to add this to the documentation so people learn about this feature? Also, in the linked ticket you stated that you found some documentation why `name` may be preferred over `id`, can you elaborate on this? Again, thanks!

**Comment by rhelms** [comment]
Will do for the divorce, when I get into work tomorrow.

With regards to name vs I'd, I saw this in a pdf man page for circo, but
each pdf for each engine tends to cover all the engines, and specifically
refers to that field as name. Unfortunately, the GraphViz site was having
issues today, but maybe I'll be able to reference doco on their GitHub
account.

**Comment by rhelms** [comment]
With regards to the usage of `name` vs `id`, the [man pages](http://www.graphviz.org/pdf/circo.1.pdf) use `name` and the [abstract grammar](http://www.graphviz.org/content/dot-language) uses `ID`. 

If the `Fhaculty\Graph\Graph` accepted an `id` in the constructor or had it changeable as a property, then I would have used the constructor or methods to set the `id` and be consistent with `Vertex`. 

But since those are not there, and the `GraphViz` class is something else, going with what is in the manual pages for the installed product seemed the next best thing, for consistency.

However, if you'd really like to see it as `id`, I'd be happy to make that change. I'm just glad there's any easy to use API out there, given that PHP 7 bindings have been removed from GraphViz for the moment.

**Comment by clue** [comment]
@rhelms Again thank you for filing this PR and for your patience!

I agree that this feature makes perfect sense and have just merged a slightly modified version with #28 (with proper attribution of course) :shipit: :tada:

Thanks for your investigation! Interestingly, https://www.graphviz.org/doc/info/lang.html and also https://graphviz.readthedocs.io/en/stable/manual.html#basic-usage suggest that the root graph name is actually optional. Accordingly, I've changed this to omit the default "G" root graph name by default and otherwise added documentation for the new `graphviz.name` attribute as introduced in this PR.

This means that this now works as expected out of the box and there should be no need to change this for most common use cases. Again, thank you! :+1:

**Pull request closed without merging**
